PizzaHut/Controllers/CheckoutController.cs
using Newtonsoft.Json.Linq;
using PizzaHut.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PizzaHut.Controllers
{
    public class CheckoutController : Controller
    {
        private const string SessionCart = "SessionCart";
        BookstoreDbContext db = new BookstoreDbContext();
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public ActionResult Index()
        {
            var cart = Session[SessionCart];
            var list = new List<Cart_item>();
            if (cart != null)
            {
                list = (List<Cart_item>)cart;
            }
            else
            {
                ViewBag.error = "Chưa có sản phẩm nào trong giỏ";
                return View(list);
            }
            ViewBag.error = "";
          
            return View(list);

        }
        [HttpPost]
        public ActionResult formCheckOut(FormCollection f)
        {
            //Muser user = (Muser)Session[Common.CommonConstants.CUSTOMER_SESSION];
            var tenKH = f["deliveryname"];
            var SDT = f["deliveryphone"];
            var email = f["deliveryemail"];
            var diaChi = f["deliveryaddress"];
            var TongTien = f["sumOrder"];
            Morder order = new Morder();
            order.deliveryname = tenKH;
            order.deliveryphone = SDT;
            order.deliveryemail = email;
            order.deliveryaddress = diaChi;
            order.updated_at = DateTime.Today;
            db.Orders.Add(order);
            db.SaveChanges();
            var cart = Session[SessionCart];
            var list1 = new List<Cart_item>();
            if (cart != null)
            {
                list1 = (List<Cart_item>)cart;
            }
            var orderid = db.Orders.OrderByDescending(m => m.ID).ToList()[0].ID;
            foreach(var item in list1)
            {
                Mordersdetail detail = new Mordersdetail();
                detail.orderid = orderid;
                detail.productid = item.product.ID;
                detail.price = item.product.price;
                detail.quantity = item.quantity;
                detail.priceSale = item.product.pricesale;
                detail.amount = (detail.price * (100 - detail.priceSale) / 100)*detail.quantity;
                db.Ordersdetails.Add(detail);
                db.SaveChanges();
            }
            Session[SessionCart] = null;
            return View("OrderComplete");
        }

    }
}

PizzaHut/Views/Checkout/Index.cshtml
@model List<PizzaHut.Models.Cart_item>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layoutSite.cshtml";

}
<link href="~/Public/css/cssNganLuong.css" rel="stylesheet" />
<section class="breadcrumb-section bg-white">
    <h2 class="sr-only">Site Breadcrumb</h2>
    <div class="container">
        <div class="breadcrumb-contents">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Thanh toán</li>
                </ol>
            </nav>
        </div>
    </div>
</section>
<main id="content" class="page-section inner-page-sec-padding-bottom space-db--20 ">
    <div class="container bg-white card">
        <div class="row">
            <form action="~/Checkout/formCheckOut" method="POST">
                <div class="col-12">
                    <!-- Checkout Form s-->
                    <div class="checkout-form">
                        <div class="row row-40">
                            <div class="col-12">
                                <h1 class="quick-title">Thanh toán</h1>

                           
                            </div>
                            <div class="col-lg-7 mb--20">
                                <!-- Billing Address -->

                                <div id="billing-form" class="mb-40">
                                    <h4 class="checkout-title text-danger ">Thông tin giao hàng</h4>
                                    <div class="row">

                                        <div class="col-12 mb--20">
                                            <label>Họ tên bạn  <span class="text-danger">*</span></label>
                                            <input type="text" name="deliveryname" value="" placeholder="Họ tên bạn" required>
                                        </div>

                                        <div class="col-md-6 col-12 mb--20">
                                            <label>Địa chỉ email <span class="text-danger">*</span></label>
                                            <input type="email" value="" name="deliveryemail" placeholder="Địa chỉ email" required>
                                        </div>
                                        <div class="col-md-6 col-12 mb--20">
                                            <label>Số điện thoại nhận hàng <span class="text-danger">*</span></label>
                                            <input type="text" name="deliveryphone" value="" placeholder="Số điện thoại nhận hàng" required>
                                        </div>
                                        <div class="col-12 mb--20">
                                            <label>Địa chỉ  <span class="text-danger">*</span></label>
                                            <input type="text" name="deliveryaddress" value="" placeholder="Địa chỉ" required>
                                        </div>
                                    </div>
                                </div>
                                <!-- Slide Down Trigger  -->

                            </div>
                         

                            <div class="col-lg-5">
                                <div class="row">
                                    <!-- Cart Total -->
                                    <div class="col-12">
                                        <div class="checkout-cart-total">

                                            <h2 class="checkout-title">Giỏ hàng</h2>
                                            <h4>Sản phẩm <span>Tổng</span></h4>

                                            @if (ViewBag.error == "")
                                            {
                                                float sum = 0;
                                                foreach (var iten in Model)
                                                {
                                                    int sale = (int)iten.product.pricesale;
                                                    float price = (int)iten.product.price - (int)iten.product.price / 100 * (int)sale;
                                                    float price1 = ((int)iten.product.price - (int)iten.product.price / 100 * (int)sale) * (iten.quantity);
                                                    sum += price * (int)iten.quantity;
                                                    <ul>
                                                        <li>
                                                            <span class="left text-success">@iten.product.name  X @iten.quantity</span> <span class="right">@price1.ToString("N0") VND</span>
                                                        </li>
                                                    </ul>
                                                }
                                                <p>Tạm tính <span>@sum.ToString("N0") VND</span></p>
                                                <p>Tiền shipping <span>0 VND</span></p>
                                                <input type="hidden" value="@sum" name="sumOrder"/>
                                                <h4>Tổng tiền <span>@sum.ToString("N0") VND</span></h4>

                                            }
                                            else
                                            {
                                                <span class="text-danger">@ViewBag.error</span>
                                            }



                                            <div class="term-block">
                                                <input type="checkbox" id="accept_terms2" required="">
                                                <label for="accept_terms2">
                                                    Tôi đã đọc và chấp nhận các điều khoản và điều kiện
                                                </label>
                                            </div>
                                            @if (ViewBag.error == "")
                                            {
                                                <button type="submit" class="place-order w-100">Đặt hàng</button>
                                            }
                                            else
                                            {
                                                <button type="button" onclick="CheckCart()" class="place-order w-100">Đặt hàng</button>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </>
            </div>
            </div>
    </main>
<script>
    function CheckCart() {
        alertify.error(" Bạn phải thêm sản phẩm vào giỏ hàng");
        return false;
    }
</script>

PizzaHut/Views/Checkout/_formCheckout.cshtml
@{
    ViewBag.Title = "formCheckOut";
    Layout = "~/Views/Shared/_layoutSite.cshtml";
}

<section class="breadcrumb-section">
    <h2 class="sr-only">Site Breadcrumb</h2>
    <div class="container">
        <div class="breadcrumb-contents">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Đặt hàng thành công</li>
                </ol>
            </nav>
        </div>
    </div>
</section>

<!-- order complete Page Start -->
<section class="order-complete inner-page-sec-padding-bottom">
    <div class="container bg-white">
        <div class="row">
            <div class="col-12">
                <div class="order-complete-message text-center">
                    <h1>Thank you !</h1>
                    <p>Đã nhận được đơn đặt hàng của bạn.</p>
                </div>
            </div>
        </div>
    </div>
</section>

PizzaHut/Views/Checkout/_productDetailCheckOut.cshtml
@model IEnumerable<PizzaHut.Models.Mordersdetail>
<table class="table order-details-table">
    <thead>
        <tr>
            <th>Sản phẩm</th>
            <th>Tổng tiền</th>
        </tr>
    </thead>
    <tbody>
        @{ int sum = 0;}
        @foreach (var item in Model)
        {
            sum += (int)item.amount;
            <tr>
                <td> 
                @Html.Action("subnameProduct", "Checkout", new { id = item.productid })  
                <strong>× @item.quantity</strong></td>
                <td><span>@item.amount.ToString("N0") VND</span></td>
            </tr>
        }

    </tbody>
    <tfoot>
        <tr>
            <th>Tạm tính:</th>
            <td><span>@sum.ToString("N0") VND</span></td>
        </tr>
        <tr>
            <th>Phương thức thanh toán:</th>
            <td>Thanh toán khi nhận hàng</td>
        </tr>
        <tr>
            <th>Tổng:</th>
            <td><span>@sum.ToString("N0") VND</span></td>
        </tr>
    </tfoot>
</table>

PizzaHut/Views/Checkout/_subproductOrdersuccess.cshtml
@model PizzaHut.Models.Product

<a href="~/san-pham/@Model">@Model.name</a>

PizzaHut/Views/Checkout/cancel_order.cshtml
<section class="pt-5">
    <div class="container bg-white">
        <span>Hủy thanh toán thành công <a class="text-danger" href="~/">Về trang chủ</a></span>

    </div>
</section>

PizzaHut/Views/Checkout/orderComplete.cshtml
@model PizzaHut.Models.Morder
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layoutSite.cshtml";
}
<section class="breadcrumb-section">
    <h2 class="sr-only">Site Breadcrumb</h2>
    <div class="container">
        <div class="breadcrumb-contents">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Đặt hàng thành công</li>
                </ol>
            </nav>
        </div>
    </div>
</section>

<!-- order complete Page Start -->
<section class="order-complete inner-page-sec-padding-bottom">
    <div class="container bg-white">
        <div class="row">
            <div class="col-12">
                <div class="order-complete-message text-center">
                    <h1>Thank you !</h1>
                    <p>Đã nhận được đơn đặt hàng của bạn.</p>
                </div>
            </div>
        </div>
    </div>
</section>